output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = "${module.eks.cluster_endpoint}"
}

# output "kubectl_config" {
#   description = "kubectl config as generated by the module."
#   value       = "${module.eks.kubeconfig}"
# }

output "ecr_repository_url" {
  description = "ECR repository url."
  value = aws_ecr_repository.active-ecr.repository_url
}