name: check changes on branch

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    name: Build and Deploy Apps 
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Get Changed Files
      id: changed-files
      uses: tj-actions/changed-files@v37
      with:
        files_yaml: |
          server:
            - server/**


    - name: Build and Deploy server
      if: steps.changed-files.outputs.server_any_changed == 'true'
      run: |

         docker build
          
